server:
  port: 8086
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    localdatasource:
      url: jdbc:mysql://localhost:3306/arknights?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver

scheduled:
# 每天4点抽卡次数清空
  cleanJob: 0 0 4 */1 * ?
  countJob: 0 0 20 */1 * ?
userConfig:
# 每日抽卡的限制次数
  limit: 20
#登录的机器人qq
  loginQq: 3022645754
#OPQ框架部署的IP
  OPQUrl: localhost
baiduConfig:
  APP_ID: 23153443
  API_KEY: Ah79wgMEgvkCr4xq4gpDvx86
  SECRET_KEY: j3MOO7nWneF6zOuVxpT2S7gQbaPMn3Dc