server:
  port: 8086
spring:
  datasource:
    localdatasource:
      url: jdbc:mysql://localhost:3306/arknights?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver

scheduled:
# 每天4点抽卡次数清空
  cleanJob: 0 0 4 */1 * ?
userConfig:
# 每日抽卡的限制次数
  limit: 20
#登录的机器人qq
  loginQq: 3022645754